package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_command.proto

public final class BtCommand {
    private BtCommand() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * Protobuf enum {@code _command}
     */
    public enum _command
            implements com.google.protobuf.Internal.EnumLite {
        /**
         * <code>reboot = 1;</code>
         */
        reboot(0, 1),
        /**
         * <code>screen_on = 2;</code>
         */
        screen_on(1, 2),
        /**
         * <code>read_acc = 3;</code>
         */
        read_acc(2, 3),
        /**
         * <code>stop_acc = 4;</code>
         */
        stop_acc(3, 4),
        /**
         * <code>motor_on = 5;</code>
         */
        motor_on(4, 5),
        /**
         * <code>factory_set = 6;</code>
         */
        factory_set(5, 6),
        /**
         * <code>show_course_card = 7;</code>
         */
        show_course_card(6, 7),
        /**
         * <code>jump_to_bootloader = 8;</code>
         */
        jump_to_bootloader(7, 8),;

        /**
         * <code>reboot = 1;</code>
         */
        public static final int reboot_VALUE = 1;
        /**
         * <code>screen_on = 2;</code>
         */
        public static final int screen_on_VALUE = 2;
        /**
         * <code>read_acc = 3;</code>
         */
        public static final int read_acc_VALUE = 3;
        /**
         * <code>stop_acc = 4;</code>
         */
        public static final int stop_acc_VALUE = 4;
        /**
         * <code>motor_on = 5;</code>
         */
        public static final int motor_on_VALUE = 5;
        /**
         * <code>factory_set = 6;</code>
         */
        public static final int factory_set_VALUE = 6;
        /**
         * <code>show_course_card = 7;</code>
         */
        public static final int show_course_card_VALUE = 7;
        /**
         * <code>jump_to_bootloader = 8;</code>
         */
        public static final int jump_to_bootloader_VALUE = 8;


        public final int getNumber() {
            return value;
        }

        public static _command valueOf(int value) {
            switch (value) {
                case 1:
                    return reboot;
                case 2:
                    return screen_on;
                case 3:
                    return read_acc;
                case 4:
                    return stop_acc;
                case 5:
                    return motor_on;
                case 6:
                    return factory_set;
                case 7:
                    return show_course_card;
                case 8:
                    return jump_to_bootloader;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<_command>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<_command>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<_command>() {
                    public _command findValueByNumber(int number) {
                        return _command.valueOf(number);
                    }
                };

        private final int value;

        _command(int index, int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:_command)
    }

    /**
     * Protobuf enum {@code _error_code}
     */
    public enum _error_code
            implements com.google.protobuf.Internal.EnumLite {
        /**
         * <code>success = 0;</code>
         */
        success(0, 0),
        /**
         * <code>not_support = 1;</code>
         */
        not_support(1, 1),
        /**
         * <code>not_success = 2;</code>
         */
        not_success(2, 2),;

        /**
         * <code>success = 0;</code>
         */
        public static final int success_VALUE = 0;
        /**
         * <code>not_support = 1;</code>
         */
        public static final int not_support_VALUE = 1;
        /**
         * <code>not_success = 2;</code>
         */
        public static final int not_success_VALUE = 2;


        public final int getNumber() {
            return value;
        }

        public static _error_code valueOf(int value) {
            switch (value) {
                case 0:
                    return success;
                case 1:
                    return not_support;
                case 2:
                    return not_success;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<_error_code>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<_error_code>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<_error_code>() {
                    public _error_code findValueByNumber(int number) {
                        return _error_code.valueOf(number);
                    }
                };

        private final int value;

        _error_code(int index, int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:_error_code)
    }

    public interface bt_command_reqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_command_req)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        boolean hasCommandId();

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        _command getCommandId();
    }

    /**
     * Protobuf type {@code bt_command_req}
     */
    public static final class bt_command_req extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_command_req)
            bt_command_reqOrBuilder {
        // Use bt_command_req.newBuilder() to construct.
        private bt_command_req(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_command_req(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_command_req defaultInstance;

        public static bt_command_req getDefaultInstance() {
            return defaultInstance;
        }

        public bt_command_req getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_command_req(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            _command value = _command.valueOf(rawValue);
                            if (value == null) {
                                unknownFieldsCodedOutput.writeRawVarint32(tag);
                                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                commandId_ = value;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_command_req> PARSER =
                new com.google.protobuf.AbstractParser<bt_command_req>() {
                    public bt_command_req parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_command_req(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_command_req> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int COMMAND_ID_FIELD_NUMBER = 1;
        private _command commandId_;

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        public boolean hasCommandId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        public _command getCommandId() {
            return commandId_;
        }

        private void initFields() {
            commandId_ = _command.reboot;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, commandId_.getNumber());
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, commandId_.getNumber());
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_command_req parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_command_req parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_command_req parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_command_req parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_command_req parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_command_req parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_command_req parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_command_req parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_command_req parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_command_req parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_command_req prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_command_req}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_command_req, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_command_req)
                bt_command_reqOrBuilder {
            // Construct using BtCommand.bt_command_req.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                commandId_ = _command.reboot;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_command_req getDefaultInstanceForType() {
                return bt_command_req.getDefaultInstance();
            }

            public bt_command_req build() {
                bt_command_req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_command_req buildPartial() {
                bt_command_req result = new bt_command_req(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.commandId_ = commandId_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_command_req other) {
                if (other == bt_command_req.getDefaultInstance()) return this;
                if (other.hasCommandId()) {
                    setCommandId(other.getCommandId());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_command_req parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_command_req) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private _command commandId_ = _command.reboot;

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public boolean hasCommandId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public _command getCommandId() {
                return commandId_;
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public Builder setCommandId(_command value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                commandId_ = value;

                return this;
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public Builder clearCommandId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                commandId_ = _command.reboot;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_command_req)
        }

        static {
            defaultInstance = new bt_command_req(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_command_req)
    }

    public interface bt_command_rspOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_command_rsp)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        boolean hasCommandId();

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        _command getCommandId();

        /**
         * <code>optional ._error_code error_code = 2;</code>
         */
        boolean hasErrorCode();

        /**
         * <code>optional ._error_code error_code = 2;</code>
         */
        _error_code getErrorCode();
    }

    /**
     * Protobuf type {@code bt_command_rsp}
     */
    public static final class bt_command_rsp extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_command_rsp)
            bt_command_rspOrBuilder {
        // Use bt_command_rsp.newBuilder() to construct.
        private bt_command_rsp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_command_rsp(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_command_rsp defaultInstance;

        public static bt_command_rsp getDefaultInstance() {
            return defaultInstance;
        }

        public bt_command_rsp getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_command_rsp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            _command value = _command.valueOf(rawValue);
                            if (value == null) {
                                unknownFieldsCodedOutput.writeRawVarint32(tag);
                                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                commandId_ = value;
                            }
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            _error_code value = _error_code.valueOf(rawValue);
                            if (value == null) {
                                unknownFieldsCodedOutput.writeRawVarint32(tag);
                                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                errorCode_ = value;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_command_rsp> PARSER =
                new com.google.protobuf.AbstractParser<bt_command_rsp>() {
                    public bt_command_rsp parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_command_rsp(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_command_rsp> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int COMMAND_ID_FIELD_NUMBER = 1;
        private _command commandId_;

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        public boolean hasCommandId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional ._command command_id = 1;</code>
         */
        public _command getCommandId() {
            return commandId_;
        }

        public static final int ERROR_CODE_FIELD_NUMBER = 2;
        private _error_code errorCode_;

        /**
         * <code>optional ._error_code error_code = 2;</code>
         */
        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional ._error_code error_code = 2;</code>
         */
        public _error_code getErrorCode() {
            return errorCode_;
        }

        private void initFields() {
            commandId_ = _command.reboot;
            errorCode_ = _error_code.success;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, commandId_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeEnum(2, errorCode_.getNumber());
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, commandId_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, errorCode_.getNumber());
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_command_rsp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_command_rsp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_command_rsp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_command_rsp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_command_rsp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_command_rsp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_command_rsp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_command_rsp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_command_rsp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_command_rsp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_command_rsp prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_command_rsp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_command_rsp, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_command_rsp)
                bt_command_rspOrBuilder {
            // Construct using BtCommand.bt_command_rsp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                commandId_ = _command.reboot;
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = _error_code.success;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_command_rsp getDefaultInstanceForType() {
                return bt_command_rsp.getDefaultInstance();
            }

            public bt_command_rsp build() {
                bt_command_rsp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_command_rsp buildPartial() {
                bt_command_rsp result = new bt_command_rsp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.commandId_ = commandId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.errorCode_ = errorCode_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_command_rsp other) {
                if (other == bt_command_rsp.getDefaultInstance()) return this;
                if (other.hasCommandId()) {
                    setCommandId(other.getCommandId());
                }
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_command_rsp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_command_rsp) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private _command commandId_ = _command.reboot;

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public boolean hasCommandId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public _command getCommandId() {
                return commandId_;
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public Builder setCommandId(_command value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                commandId_ = value;

                return this;
            }

            /**
             * <code>optional ._command command_id = 1;</code>
             */
            public Builder clearCommandId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                commandId_ = _command.reboot;

                return this;
            }

            private _error_code errorCode_ = _error_code.success;

            /**
             * <code>optional ._error_code error_code = 2;</code>
             */
            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional ._error_code error_code = 2;</code>
             */
            public _error_code getErrorCode() {
                return errorCode_;
            }

            /**
             * <code>optional ._error_code error_code = 2;</code>
             */
            public Builder setErrorCode(_error_code value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                errorCode_ = value;

                return this;
            }

            /**
             * <code>optional ._error_code error_code = 2;</code>
             */
            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                errorCode_ = _error_code.success;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_command_rsp)
        }

        static {
            defaultInstance = new bt_command_rsp(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_command_rsp)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
