package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_get_data_rsp.proto

public final class BtGetDataRsp {
    private BtGetDataRsp() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * Protobuf enum {@code ERROR_CODE}
     */
    public enum ERROR_CODE
            implements com.google.protobuf.Internal.EnumLite {
        /**
         * <code>SUCCESS = 0;</code>
         */
        SUCCESS(0, 0),
        /**
         * <code>DATA_TYPE_NOT_SPUUORT = 1;</code>
         */
        DATA_TYPE_NOT_SPUUORT(1, 1),;

        /**
         * <code>SUCCESS = 0;</code>
         */
        public static final int SUCCESS_VALUE = 0;
        /**
         * <code>DATA_TYPE_NOT_SPUUORT = 1;</code>
         */
        public static final int DATA_TYPE_NOT_SPUUORT_VALUE = 1;


        public final int getNumber() {
            return value;
        }

        public static ERROR_CODE valueOf(int value) {
            switch (value) {
                case 0:
                    return SUCCESS;
                case 1:
                    return DATA_TYPE_NOT_SPUUORT;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ERROR_CODE>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<ERROR_CODE>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<ERROR_CODE>() {
                    public ERROR_CODE findValueByNumber(int number) {
                        return ERROR_CODE.valueOf(number);
                    }
                };

        private final int value;

        ERROR_CODE(int index, int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:ERROR_CODE)
    }

    public interface bt_get_data_rspOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_get_data_rsp)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .ERROR_CODE error_code = 1;</code>
         */
        boolean hasErrorCode();

        /**
         * <code>optional .ERROR_CODE error_code = 1;</code>
         */
        ERROR_CODE getErrorCode();
    }

    /**
     * Protobuf type {@code bt_get_data_rsp}
     */
    public static final class bt_get_data_rsp extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_get_data_rsp)
            bt_get_data_rspOrBuilder {
        // Use bt_get_data_rsp.newBuilder() to construct.
        private bt_get_data_rsp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_get_data_rsp(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_get_data_rsp defaultInstance;

        public static bt_get_data_rsp getDefaultInstance() {
            return defaultInstance;
        }

        public bt_get_data_rsp getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_get_data_rsp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            ERROR_CODE value = ERROR_CODE.valueOf(rawValue);
                            if (value == null) {
                                unknownFieldsCodedOutput.writeRawVarint32(tag);
                                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                errorCode_ = value;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_get_data_rsp> PARSER =
                new com.google.protobuf.AbstractParser<bt_get_data_rsp>() {
                    public bt_get_data_rsp parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_get_data_rsp(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_get_data_rsp> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ERROR_CODE_FIELD_NUMBER = 1;
        private ERROR_CODE errorCode_;

        /**
         * <code>optional .ERROR_CODE error_code = 1;</code>
         */
        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .ERROR_CODE error_code = 1;</code>
         */
        public ERROR_CODE getErrorCode() {
            return errorCode_;
        }

        private void initFields() {
            errorCode_ = ERROR_CODE.SUCCESS;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, errorCode_.getNumber());
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, errorCode_.getNumber());
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_get_data_rsp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_get_data_rsp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_get_data_rsp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_get_data_rsp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_get_data_rsp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_get_data_rsp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_get_data_rsp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_get_data_rsp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_get_data_rsp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_get_data_rsp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_get_data_rsp prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_get_data_rsp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_get_data_rsp, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_get_data_rsp)
                bt_get_data_rspOrBuilder {
            // Construct using BtGetDataRsp.bt_get_data_rsp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                errorCode_ = ERROR_CODE.SUCCESS;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_get_data_rsp getDefaultInstanceForType() {
                return bt_get_data_rsp.getDefaultInstance();
            }

            public bt_get_data_rsp build() {
                bt_get_data_rsp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_get_data_rsp buildPartial() {
                bt_get_data_rsp result = new bt_get_data_rsp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.errorCode_ = errorCode_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_get_data_rsp other) {
                if (other == bt_get_data_rsp.getDefaultInstance()) return this;
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_get_data_rsp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_get_data_rsp) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private ERROR_CODE errorCode_ = ERROR_CODE.SUCCESS;

            /**
             * <code>optional .ERROR_CODE error_code = 1;</code>
             */
            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .ERROR_CODE error_code = 1;</code>
             */
            public ERROR_CODE getErrorCode() {
                return errorCode_;
            }

            /**
             * <code>optional .ERROR_CODE error_code = 1;</code>
             */
            public Builder setErrorCode(ERROR_CODE value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                errorCode_ = value;

                return this;
            }

            /**
             * <code>optional .ERROR_CODE error_code = 1;</code>
             */
            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = ERROR_CODE.SUCCESS;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_get_data_rsp)
        }

        static {
            defaultInstance = new bt_get_data_rsp(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_get_data_rsp)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
