package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_nx2_watch_skin.proto

public final class BtNx2WatchSkin {
    private BtNx2WatchSkin() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * Protobuf enum {@code bt_nx2_watch_skin_return}
     */
    public enum bt_nx2_watch_skin_return
            implements com.google.protobuf.Internal.EnumLite {
        /**
         * <code>success = 0;</code>
         */
        success(0, 0),
        /**
         * <code>no_this_face = 1;</code>
         */
        no_this_face(1, 1),
        /**
         * <code>other = 2;</code>
         * <p/>
         * <pre>
         * </pre>
         */
        other(2, 2),;

        /**
         * <code>success = 0;</code>
         */
        public static final int success_VALUE = 0;
        /**
         * <code>no_this_face = 1;</code>
         */
        public static final int no_this_face_VALUE = 1;
        /**
         * <code>other = 2;</code>
         * <p/>
         * <pre>
         * </pre>
         */
        public static final int other_VALUE = 2;


        public final int getNumber() {
            return value;
        }

        public static bt_nx2_watch_skin_return valueOf(int value) {
            switch (value) {
                case 0:
                    return success;
                case 1:
                    return no_this_face;
                case 2:
                    return other;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<bt_nx2_watch_skin_return>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<bt_nx2_watch_skin_return>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<bt_nx2_watch_skin_return>() {
                    public bt_nx2_watch_skin_return findValueByNumber(int number) {
                        return bt_nx2_watch_skin_return.valueOf(number);
                    }
                };

        private final int value;

        bt_nx2_watch_skin_return(int index, int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:bt_nx2_watch_skin_return)
    }

    public interface bt_nx2_watch_skin_switchOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_nx2_watch_skin_switch)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        boolean hasInfo();

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        nx2_watch getInfo();
    }

    /**
     * Protobuf type {@code bt_nx2_watch_skin_switch}
     */
    public static final class bt_nx2_watch_skin_switch extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_nx2_watch_skin_switch)
            bt_nx2_watch_skin_switchOrBuilder {
        // Use bt_nx2_watch_skin_switch.newBuilder() to construct.
        private bt_nx2_watch_skin_switch(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_nx2_watch_skin_switch(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_nx2_watch_skin_switch defaultInstance;

        public static bt_nx2_watch_skin_switch getDefaultInstance() {
            return defaultInstance;
        }

        public bt_nx2_watch_skin_switch getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_nx2_watch_skin_switch(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            nx2_watch.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                                subBuilder = info_.toBuilder();
                            }
                            info_ = input.readMessage(nx2_watch.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(info_);
                                info_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_nx2_watch_skin_switch> PARSER =
                new com.google.protobuf.AbstractParser<bt_nx2_watch_skin_switch>() {
                    public bt_nx2_watch_skin_switch parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_nx2_watch_skin_switch(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_nx2_watch_skin_switch> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int INFO_FIELD_NUMBER = 1;
        private nx2_watch info_;

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        public boolean hasInfo() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        public nx2_watch getInfo() {
            return info_;
        }

        private void initFields() {
            info_ = nx2_watch.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, info_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, info_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_switch parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_switch parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_switch parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_nx2_watch_skin_switch parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_switch parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_nx2_watch_skin_switch prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_nx2_watch_skin_switch}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_nx2_watch_skin_switch, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_nx2_watch_skin_switch)
                bt_nx2_watch_skin_switchOrBuilder {
            // Construct using BtNx2WatchSkin.bt_nx2_watch_skin_switch.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                info_ = nx2_watch.getDefaultInstance();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_nx2_watch_skin_switch getDefaultInstanceForType() {
                return bt_nx2_watch_skin_switch.getDefaultInstance();
            }

            public bt_nx2_watch_skin_switch build() {
                bt_nx2_watch_skin_switch result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_nx2_watch_skin_switch buildPartial() {
                bt_nx2_watch_skin_switch result = new bt_nx2_watch_skin_switch(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.info_ = info_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_nx2_watch_skin_switch other) {
                if (other == bt_nx2_watch_skin_switch.getDefaultInstance()) return this;
                if (other.hasInfo()) {
                    mergeInfo(other.getInfo());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_nx2_watch_skin_switch parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_nx2_watch_skin_switch) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private nx2_watch info_ = nx2_watch.getDefaultInstance();

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public boolean hasInfo() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public nx2_watch getInfo() {
                return info_;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder setInfo(nx2_watch value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                info_ = value;

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder setInfo(
                    nx2_watch.Builder builderForValue) {
                info_ = builderForValue.build();

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder mergeInfo(nx2_watch value) {
                if (((bitField0_ & 0x00000001) == 0x00000001) &&
                        info_ != nx2_watch.getDefaultInstance()) {
                    info_ =
                            nx2_watch.newBuilder(info_).mergeFrom(value).buildPartial();
                } else {
                    info_ = value;
                }

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder clearInfo() {
                info_ = nx2_watch.getDefaultInstance();

                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_nx2_watch_skin_switch)
        }

        static {
            defaultInstance = new bt_nx2_watch_skin_switch(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_nx2_watch_skin_switch)
    }

    public interface bt_nx2_watch_skin_rspOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_nx2_watch_skin_rsp)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
         */
        boolean hasReturnCode();

        /**
         * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
         */
        bt_nx2_watch_skin_return getReturnCode();
    }

    /**
     * Protobuf type {@code bt_nx2_watch_skin_rsp}
     */
    public static final class bt_nx2_watch_skin_rsp extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_nx2_watch_skin_rsp)
            bt_nx2_watch_skin_rspOrBuilder {
        // Use bt_nx2_watch_skin_rsp.newBuilder() to construct.
        private bt_nx2_watch_skin_rsp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_nx2_watch_skin_rsp(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_nx2_watch_skin_rsp defaultInstance;

        public static bt_nx2_watch_skin_rsp getDefaultInstance() {
            return defaultInstance;
        }

        public bt_nx2_watch_skin_rsp getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_nx2_watch_skin_rsp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            bt_nx2_watch_skin_return value = bt_nx2_watch_skin_return.valueOf(rawValue);
                            if (value == null) {
                                unknownFieldsCodedOutput.writeRawVarint32(tag);
                                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                returnCode_ = value;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_nx2_watch_skin_rsp> PARSER =
                new com.google.protobuf.AbstractParser<bt_nx2_watch_skin_rsp>() {
                    public bt_nx2_watch_skin_rsp parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_nx2_watch_skin_rsp(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_nx2_watch_skin_rsp> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int RETURN_CODE_FIELD_NUMBER = 1;
        private bt_nx2_watch_skin_return returnCode_;

        /**
         * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
         */
        public boolean hasReturnCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
         */
        public bt_nx2_watch_skin_return getReturnCode() {
            return returnCode_;
        }

        private void initFields() {
            returnCode_ = bt_nx2_watch_skin_return.success;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, returnCode_.getNumber());
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, returnCode_.getNumber());
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_rsp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_nx2_watch_skin_rsp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_rsp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_nx2_watch_skin_rsp prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_nx2_watch_skin_rsp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_nx2_watch_skin_rsp, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_nx2_watch_skin_rsp)
                bt_nx2_watch_skin_rspOrBuilder {
            // Construct using BtNx2WatchSkin.bt_nx2_watch_skin_rsp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                returnCode_ = bt_nx2_watch_skin_return.success;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_nx2_watch_skin_rsp getDefaultInstanceForType() {
                return bt_nx2_watch_skin_rsp.getDefaultInstance();
            }

            public bt_nx2_watch_skin_rsp build() {
                bt_nx2_watch_skin_rsp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_nx2_watch_skin_rsp buildPartial() {
                bt_nx2_watch_skin_rsp result = new bt_nx2_watch_skin_rsp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.returnCode_ = returnCode_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_nx2_watch_skin_rsp other) {
                if (other == bt_nx2_watch_skin_rsp.getDefaultInstance()) return this;
                if (other.hasReturnCode()) {
                    setReturnCode(other.getReturnCode());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_nx2_watch_skin_rsp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_nx2_watch_skin_rsp) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private bt_nx2_watch_skin_return returnCode_ = bt_nx2_watch_skin_return.success;

            /**
             * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
             */
            public boolean hasReturnCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
             */
            public bt_nx2_watch_skin_return getReturnCode() {
                return returnCode_;
            }

            /**
             * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
             */
            public Builder setReturnCode(bt_nx2_watch_skin_return value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                returnCode_ = value;

                return this;
            }

            /**
             * <code>optional .bt_nx2_watch_skin_return return_code = 1;</code>
             */
            public Builder clearReturnCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                returnCode_ = bt_nx2_watch_skin_return.success;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_nx2_watch_skin_rsp)
        }

        static {
            defaultInstance = new bt_nx2_watch_skin_rsp(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_nx2_watch_skin_rsp)
    }

    public interface bt_nx2_watch_skin_currentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_nx2_watch_skin_current)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        boolean hasInfo();

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        nx2_watch getInfo();
    }

    /**
     * Protobuf type {@code bt_nx2_watch_skin_current}
     */
    public static final class bt_nx2_watch_skin_current extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_nx2_watch_skin_current)
            bt_nx2_watch_skin_currentOrBuilder {
        // Use bt_nx2_watch_skin_current.newBuilder() to construct.
        private bt_nx2_watch_skin_current(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_nx2_watch_skin_current(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_nx2_watch_skin_current defaultInstance;

        public static bt_nx2_watch_skin_current getDefaultInstance() {
            return defaultInstance;
        }

        public bt_nx2_watch_skin_current getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_nx2_watch_skin_current(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            nx2_watch.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                                subBuilder = info_.toBuilder();
                            }
                            info_ = input.readMessage(nx2_watch.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(info_);
                                info_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_nx2_watch_skin_current> PARSER =
                new com.google.protobuf.AbstractParser<bt_nx2_watch_skin_current>() {
                    public bt_nx2_watch_skin_current parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_nx2_watch_skin_current(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_nx2_watch_skin_current> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int INFO_FIELD_NUMBER = 1;
        private nx2_watch info_;

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        public boolean hasInfo() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .nx2_watch info = 1;</code>
         */
        public nx2_watch getInfo() {
            return info_;
        }

        private void initFields() {
            info_ = nx2_watch.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, info_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, info_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_nx2_watch_skin_current parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_current parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_current parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_nx2_watch_skin_current parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_nx2_watch_skin_current parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_current parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_current parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_nx2_watch_skin_current parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_nx2_watch_skin_current parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_nx2_watch_skin_current parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_nx2_watch_skin_current prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_nx2_watch_skin_current}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_nx2_watch_skin_current, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_nx2_watch_skin_current)
                bt_nx2_watch_skin_currentOrBuilder {
            // Construct using BtNx2WatchSkin.bt_nx2_watch_skin_current.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                info_ = nx2_watch.getDefaultInstance();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_nx2_watch_skin_current getDefaultInstanceForType() {
                return bt_nx2_watch_skin_current.getDefaultInstance();
            }

            public bt_nx2_watch_skin_current build() {
                bt_nx2_watch_skin_current result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_nx2_watch_skin_current buildPartial() {
                bt_nx2_watch_skin_current result = new bt_nx2_watch_skin_current(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.info_ = info_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_nx2_watch_skin_current other) {
                if (other == bt_nx2_watch_skin_current.getDefaultInstance()) return this;
                if (other.hasInfo()) {
                    mergeInfo(other.getInfo());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_nx2_watch_skin_current parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_nx2_watch_skin_current) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private nx2_watch info_ = nx2_watch.getDefaultInstance();

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public boolean hasInfo() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public nx2_watch getInfo() {
                return info_;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder setInfo(nx2_watch value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                info_ = value;

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder setInfo(
                    nx2_watch.Builder builderForValue) {
                info_ = builderForValue.build();

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder mergeInfo(nx2_watch value) {
                if (((bitField0_ & 0x00000001) == 0x00000001) &&
                        info_ != nx2_watch.getDefaultInstance()) {
                    info_ =
                            nx2_watch.newBuilder(info_).mergeFrom(value).buildPartial();
                } else {
                    info_ = value;
                }

                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .nx2_watch info = 1;</code>
             */
            public Builder clearInfo() {
                info_ = nx2_watch.getDefaultInstance();

                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_nx2_watch_skin_current)
        }

        static {
            defaultInstance = new bt_nx2_watch_skin_current(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_nx2_watch_skin_current)
    }

    public interface nx2_watchOrBuilder extends
            // @@protoc_insertion_point(interface_extends:nx2_watch)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional bytes uuid = 1;</code>
         */
        boolean hasUuid();

        /**
         * <code>optional bytes uuid = 1;</code>
         */
        com.google.protobuf.ByteString getUuid();
    }

    /**
     * Protobuf type {@code nx2_watch}
     */
    public static final class nx2_watch extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:nx2_watch)
            nx2_watchOrBuilder {
        // Use nx2_watch.newBuilder() to construct.
        private nx2_watch(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private nx2_watch(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final nx2_watch defaultInstance;

        public static nx2_watch getDefaultInstance() {
            return defaultInstance;
        }

        public nx2_watch getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private nx2_watch(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            uuid_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<nx2_watch> PARSER =
                new com.google.protobuf.AbstractParser<nx2_watch>() {
                    public nx2_watch parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new nx2_watch(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<nx2_watch> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int UUID_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString uuid_;

        /**
         * <code>optional bytes uuid = 1;</code>
         */
        public boolean hasUuid() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional bytes uuid = 1;</code>
         */
        public com.google.protobuf.ByteString getUuid() {
            return uuid_;
        }

        private void initFields() {
            uuid_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, uuid_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, uuid_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static nx2_watch parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static nx2_watch parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static nx2_watch parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static nx2_watch parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static nx2_watch parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static nx2_watch parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static nx2_watch parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static nx2_watch parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static nx2_watch parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static nx2_watch parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(nx2_watch prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code nx2_watch}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        nx2_watch, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:nx2_watch)
                nx2_watchOrBuilder {
            // Construct using BtNx2WatchSkin.nx2_watch.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                uuid_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public nx2_watch getDefaultInstanceForType() {
                return nx2_watch.getDefaultInstance();
            }

            public nx2_watch build() {
                nx2_watch result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public nx2_watch buildPartial() {
                nx2_watch result = new nx2_watch(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.uuid_ = uuid_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(nx2_watch other) {
                if (other == nx2_watch.getDefaultInstance()) return this;
                if (other.hasUuid()) {
                    setUuid(other.getUuid());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                nx2_watch parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (nx2_watch) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes uuid = 1;</code>
             */
            public boolean hasUuid() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional bytes uuid = 1;</code>
             */
            public com.google.protobuf.ByteString getUuid() {
                return uuid_;
            }

            /**
             * <code>optional bytes uuid = 1;</code>
             */
            public Builder setUuid(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                uuid_ = value;

                return this;
            }

            /**
             * <code>optional bytes uuid = 1;</code>
             */
            public Builder clearUuid() {
                bitField0_ = (bitField0_ & ~0x00000001);
                uuid_ = getDefaultInstance().getUuid();

                return this;
            }

            // @@protoc_insertion_point(builder_scope:nx2_watch)
        }

        static {
            defaultInstance = new nx2_watch(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:nx2_watch)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
