package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_read_flash.proto

public final class BtReadFlash {
    private BtReadFlash() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface bt_read_flash_reqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_read_flash_req)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint32 start_addr = 1;</code>
         */
        boolean hasStartAddr();

        /**
         * <code>optional uint32 start_addr = 1;</code>
         */
        int getStartAddr();

        /**
         * <code>optional uint32 end_addr = 2;</code>
         */
        boolean hasEndAddr();

        /**
         * <code>optional uint32 end_addr = 2;</code>
         */
        int getEndAddr();
    }

    /**
     * Protobuf type {@code bt_read_flash_req}
     */
    public static final class bt_read_flash_req extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_read_flash_req)
            bt_read_flash_reqOrBuilder {
        // Use bt_read_flash_req.newBuilder() to construct.
        private bt_read_flash_req(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_read_flash_req(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_read_flash_req defaultInstance;

        public static bt_read_flash_req getDefaultInstance() {
            return defaultInstance;
        }

        public bt_read_flash_req getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_read_flash_req(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            startAddr_ = input.readUInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            endAddr_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_read_flash_req> PARSER =
                new com.google.protobuf.AbstractParser<bt_read_flash_req>() {
                    public bt_read_flash_req parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_read_flash_req(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_read_flash_req> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int START_ADDR_FIELD_NUMBER = 1;
        private int startAddr_;

        /**
         * <code>optional uint32 start_addr = 1;</code>
         */
        public boolean hasStartAddr() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional uint32 start_addr = 1;</code>
         */
        public int getStartAddr() {
            return startAddr_;
        }

        public static final int END_ADDR_FIELD_NUMBER = 2;
        private int endAddr_;

        /**
         * <code>optional uint32 end_addr = 2;</code>
         */
        public boolean hasEndAddr() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional uint32 end_addr = 2;</code>
         */
        public int getEndAddr() {
            return endAddr_;
        }

        private void initFields() {
            startAddr_ = 0;
            endAddr_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, startAddr_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt32(2, endAddr_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, startAddr_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, endAddr_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_read_flash_req parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_read_flash_req parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_read_flash_req parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_read_flash_req parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_read_flash_req parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_read_flash_req parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_read_flash_req parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_read_flash_req parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_read_flash_req parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_read_flash_req parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_read_flash_req prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_read_flash_req}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_read_flash_req, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_read_flash_req)
                bt_read_flash_reqOrBuilder {
            // Construct using BtReadFlash.bt_read_flash_req.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                startAddr_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                endAddr_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_read_flash_req getDefaultInstanceForType() {
                return bt_read_flash_req.getDefaultInstance();
            }

            public bt_read_flash_req build() {
                bt_read_flash_req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_read_flash_req buildPartial() {
                bt_read_flash_req result = new bt_read_flash_req(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.startAddr_ = startAddr_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.endAddr_ = endAddr_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_read_flash_req other) {
                if (other == bt_read_flash_req.getDefaultInstance()) return this;
                if (other.hasStartAddr()) {
                    setStartAddr(other.getStartAddr());
                }
                if (other.hasEndAddr()) {
                    setEndAddr(other.getEndAddr());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_read_flash_req parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_read_flash_req) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int startAddr_;

            /**
             * <code>optional uint32 start_addr = 1;</code>
             */
            public boolean hasStartAddr() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional uint32 start_addr = 1;</code>
             */
            public int getStartAddr() {
                return startAddr_;
            }

            /**
             * <code>optional uint32 start_addr = 1;</code>
             */
            public Builder setStartAddr(int value) {
                bitField0_ |= 0x00000001;
                startAddr_ = value;

                return this;
            }

            /**
             * <code>optional uint32 start_addr = 1;</code>
             */
            public Builder clearStartAddr() {
                bitField0_ = (bitField0_ & ~0x00000001);
                startAddr_ = 0;

                return this;
            }

            private int endAddr_;

            /**
             * <code>optional uint32 end_addr = 2;</code>
             */
            public boolean hasEndAddr() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional uint32 end_addr = 2;</code>
             */
            public int getEndAddr() {
                return endAddr_;
            }

            /**
             * <code>optional uint32 end_addr = 2;</code>
             */
            public Builder setEndAddr(int value) {
                bitField0_ |= 0x00000002;
                endAddr_ = value;

                return this;
            }

            /**
             * <code>optional uint32 end_addr = 2;</code>
             */
            public Builder clearEndAddr() {
                bitField0_ = (bitField0_ & ~0x00000002);
                endAddr_ = 0;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_read_flash_req)
        }

        static {
            defaultInstance = new bt_read_flash_req(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_read_flash_req)
    }

    public interface bt_read_flash_rspOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_read_flash_rsp)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint32 addr = 1;</code>
         */
        boolean hasAddr();

        /**
         * <code>optional uint32 addr = 1;</code>
         */
        int getAddr();

        /**
         * <code>optional bytes hex = 2;</code>
         */
        boolean hasHex();

        /**
         * <code>optional bytes hex = 2;</code>
         */
        com.google.protobuf.ByteString getHex();
    }

    /**
     * Protobuf type {@code bt_read_flash_rsp}
     */
    public static final class bt_read_flash_rsp extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_read_flash_rsp)
            bt_read_flash_rspOrBuilder {
        // Use bt_read_flash_rsp.newBuilder() to construct.
        private bt_read_flash_rsp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_read_flash_rsp(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_read_flash_rsp defaultInstance;

        public static bt_read_flash_rsp getDefaultInstance() {
            return defaultInstance;
        }

        public bt_read_flash_rsp getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_read_flash_rsp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            addr_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            hex_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_read_flash_rsp> PARSER =
                new com.google.protobuf.AbstractParser<bt_read_flash_rsp>() {
                    public bt_read_flash_rsp parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_read_flash_rsp(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_read_flash_rsp> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ADDR_FIELD_NUMBER = 1;
        private int addr_;

        /**
         * <code>optional uint32 addr = 1;</code>
         */
        public boolean hasAddr() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional uint32 addr = 1;</code>
         */
        public int getAddr() {
            return addr_;
        }

        public static final int HEX_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString hex_;

        /**
         * <code>optional bytes hex = 2;</code>
         */
        public boolean hasHex() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bytes hex = 2;</code>
         */
        public com.google.protobuf.ByteString getHex() {
            return hex_;
        }

        private void initFields() {
            addr_ = 0;
            hex_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, addr_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, hex_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, addr_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, hex_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_read_flash_rsp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_read_flash_rsp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_read_flash_rsp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_read_flash_rsp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_read_flash_rsp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_read_flash_rsp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_read_flash_rsp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_read_flash_rsp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_read_flash_rsp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_read_flash_rsp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_read_flash_rsp prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_read_flash_rsp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_read_flash_rsp, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_read_flash_rsp)
                bt_read_flash_rspOrBuilder {
            // Construct using BtReadFlash.bt_read_flash_rsp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                addr_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                hex_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_read_flash_rsp getDefaultInstanceForType() {
                return bt_read_flash_rsp.getDefaultInstance();
            }

            public bt_read_flash_rsp build() {
                bt_read_flash_rsp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_read_flash_rsp buildPartial() {
                bt_read_flash_rsp result = new bt_read_flash_rsp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.addr_ = addr_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.hex_ = hex_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_read_flash_rsp other) {
                if (other == bt_read_flash_rsp.getDefaultInstance()) return this;
                if (other.hasAddr()) {
                    setAddr(other.getAddr());
                }
                if (other.hasHex()) {
                    setHex(other.getHex());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_read_flash_rsp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_read_flash_rsp) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int addr_;

            /**
             * <code>optional uint32 addr = 1;</code>
             */
            public boolean hasAddr() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional uint32 addr = 1;</code>
             */
            public int getAddr() {
                return addr_;
            }

            /**
             * <code>optional uint32 addr = 1;</code>
             */
            public Builder setAddr(int value) {
                bitField0_ |= 0x00000001;
                addr_ = value;

                return this;
            }

            /**
             * <code>optional uint32 addr = 1;</code>
             */
            public Builder clearAddr() {
                bitField0_ = (bitField0_ & ~0x00000001);
                addr_ = 0;

                return this;
            }

            private com.google.protobuf.ByteString hex_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes hex = 2;</code>
             */
            public boolean hasHex() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bytes hex = 2;</code>
             */
            public com.google.protobuf.ByteString getHex() {
                return hex_;
            }

            /**
             * <code>optional bytes hex = 2;</code>
             */
            public Builder setHex(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                hex_ = value;

                return this;
            }

            /**
             * <code>optional bytes hex = 2;</code>
             */
            public Builder clearHex() {
                bitField0_ = (bitField0_ & ~0x00000002);
                hex_ = getDefaultInstance().getHex();

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_read_flash_rsp)
        }

        static {
            defaultInstance = new bt_read_flash_rsp(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_read_flash_rsp)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
