package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_smart_push.proto

public final class BtSmartPush {
    private BtSmartPush() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface bt_smart_pushOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_smart_push)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        java.util.List<smart_push_config>
        getConfigList();

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        smart_push_config getConfig(int index);

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        int getConfigCount();
    }

    /**
     * Protobuf type {@code bt_smart_push}
     */
    public static final class bt_smart_push extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_smart_push)
            bt_smart_pushOrBuilder {
        // Use bt_smart_push.newBuilder() to construct.
        private bt_smart_push(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_smart_push(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_smart_push defaultInstance;

        public static bt_smart_push getDefaultInstance() {
            return defaultInstance;
        }

        public bt_smart_push getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_smart_push(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                config_ = new java.util.ArrayList<smart_push_config>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            config_.add(input.readMessage(smart_push_config.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    config_ = java.util.Collections.unmodifiableList(config_);
                }
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_smart_push> PARSER =
                new com.google.protobuf.AbstractParser<bt_smart_push>() {
                    public bt_smart_push parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_smart_push(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_smart_push> getParserForType() {
            return PARSER;
        }

        public static final int CONFIG_FIELD_NUMBER = 1;
        private java.util.List<smart_push_config> config_;

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        public java.util.List<smart_push_config> getConfigList() {
            return config_;
        }

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        public java.util.List<? extends smart_push_configOrBuilder>
        getConfigOrBuilderList() {
            return config_;
        }

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        public int getConfigCount() {
            return config_.size();
        }

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        public smart_push_config getConfig(int index) {
            return config_.get(index);
        }

        /**
         * <code>repeated .smart_push_config config = 1;</code>
         * <p/>
         * <pre>
         * max repeated 15
         * </pre>
         */
        public smart_push_configOrBuilder getConfigOrBuilder(
                int index) {
            return config_.get(index);
        }

        private void initFields() {
            config_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < config_.size(); i++) {
                output.writeMessage(1, config_.get(i));
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < config_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, config_.get(i));
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_smart_push parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_smart_push parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_smart_push parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_smart_push parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_smart_push parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_smart_push parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_smart_push parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_smart_push parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_smart_push parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_smart_push parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_smart_push prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_smart_push}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_smart_push, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_smart_push)
                bt_smart_pushOrBuilder {
            // Construct using BtSmartPush.bt_smart_push.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                config_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_smart_push getDefaultInstanceForType() {
                return bt_smart_push.getDefaultInstance();
            }

            public bt_smart_push build() {
                bt_smart_push result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_smart_push buildPartial() {
                bt_smart_push result = new bt_smart_push(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    config_ = java.util.Collections.unmodifiableList(config_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.config_ = config_;
                return result;
            }

            public Builder mergeFrom(bt_smart_push other) {
                if (other == bt_smart_push.getDefaultInstance()) return this;
                if (!other.config_.isEmpty()) {
                    if (config_.isEmpty()) {
                        config_ = other.config_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureConfigIsMutable();
                        config_.addAll(other.config_);
                    }

                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_smart_push parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_smart_push) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<smart_push_config> config_ =
                    java.util.Collections.emptyList();

            private void ensureConfigIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    config_ = new java.util.ArrayList<smart_push_config>(config_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public java.util.List<smart_push_config> getConfigList() {
                return java.util.Collections.unmodifiableList(config_);
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public int getConfigCount() {
                return config_.size();
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public smart_push_config getConfig(int index) {
                return config_.get(index);
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder setConfig(
                    int index, smart_push_config value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureConfigIsMutable();
                config_.set(index, value);

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder setConfig(
                    int index, smart_push_config.Builder builderForValue) {
                ensureConfigIsMutable();
                config_.set(index, builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder addConfig(smart_push_config value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureConfigIsMutable();
                config_.add(value);

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder addConfig(
                    int index, smart_push_config value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureConfigIsMutable();
                config_.add(index, value);

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder addConfig(
                    smart_push_config.Builder builderForValue) {
                ensureConfigIsMutable();
                config_.add(builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder addConfig(
                    int index, smart_push_config.Builder builderForValue) {
                ensureConfigIsMutable();
                config_.add(index, builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder addAllConfig(
                    Iterable<? extends smart_push_config> values) {
                ensureConfigIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, config_);

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder clearConfig() {
                config_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);

                return this;
            }

            /**
             * <code>repeated .smart_push_config config = 1;</code>
             * <p/>
             * <pre>
             * max repeated 15
             * </pre>
             */
            public Builder removeConfig(int index) {
                ensureConfigIsMutable();
                config_.remove(index);

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_smart_push)
        }

        static {
            defaultInstance = new bt_smart_push(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_smart_push)
    }

    public interface smart_push_configOrBuilder extends
            // @@protoc_insertion_point(interface_extends:smart_push_config)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint32 cardID = 1;</code>
         */
        boolean hasCardID();

        /**
         * <code>optional uint32 cardID = 1;</code>
         */
        int getCardID();

        /**
         * <code>optional bool on = 2;</code>
         */
        boolean hasOn();

        /**
         * <code>optional bool on = 2;</code>
         */
        boolean getOn();
    }

    /**
     * Protobuf type {@code smart_push_config}
     */
    public static final class smart_push_config extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:smart_push_config)
            smart_push_configOrBuilder {
        // Use smart_push_config.newBuilder() to construct.
        private smart_push_config(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private smart_push_config(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final smart_push_config defaultInstance;

        public static smart_push_config getDefaultInstance() {
            return defaultInstance;
        }

        public smart_push_config getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private smart_push_config(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            cardID_ = input.readUInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            on_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<smart_push_config> PARSER =
                new com.google.protobuf.AbstractParser<smart_push_config>() {
                    public smart_push_config parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new smart_push_config(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<smart_push_config> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int CARDID_FIELD_NUMBER = 1;
        private int cardID_;

        /**
         * <code>optional uint32 cardID = 1;</code>
         */
        public boolean hasCardID() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional uint32 cardID = 1;</code>
         */
        public int getCardID() {
            return cardID_;
        }

        public static final int ON_FIELD_NUMBER = 2;
        private boolean on_;

        /**
         * <code>optional bool on = 2;</code>
         */
        public boolean hasOn() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bool on = 2;</code>
         */
        public boolean getOn() {
            return on_;
        }

        private void initFields() {
            cardID_ = 0;
            on_ = false;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, cardID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBool(2, on_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, cardID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, on_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static smart_push_config parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static smart_push_config parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static smart_push_config parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static smart_push_config parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static smart_push_config parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static smart_push_config parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static smart_push_config parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static smart_push_config parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static smart_push_config parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static smart_push_config parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(smart_push_config prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code smart_push_config}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        smart_push_config, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:smart_push_config)
                smart_push_configOrBuilder {
            // Construct using BtSmartPush.smart_push_config.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                cardID_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                on_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public smart_push_config getDefaultInstanceForType() {
                return smart_push_config.getDefaultInstance();
            }

            public smart_push_config build() {
                smart_push_config result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public smart_push_config buildPartial() {
                smart_push_config result = new smart_push_config(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.cardID_ = cardID_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.on_ = on_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(smart_push_config other) {
                if (other == smart_push_config.getDefaultInstance()) return this;
                if (other.hasCardID()) {
                    setCardID(other.getCardID());
                }
                if (other.hasOn()) {
                    setOn(other.getOn());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                smart_push_config parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (smart_push_config) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int cardID_;

            /**
             * <code>optional uint32 cardID = 1;</code>
             */
            public boolean hasCardID() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional uint32 cardID = 1;</code>
             */
            public int getCardID() {
                return cardID_;
            }

            /**
             * <code>optional uint32 cardID = 1;</code>
             */
            public Builder setCardID(int value) {
                bitField0_ |= 0x00000001;
                cardID_ = value;

                return this;
            }

            /**
             * <code>optional uint32 cardID = 1;</code>
             */
            public Builder clearCardID() {
                bitField0_ = (bitField0_ & ~0x00000001);
                cardID_ = 0;

                return this;
            }

            private boolean on_;

            /**
             * <code>optional bool on = 2;</code>
             */
            public boolean hasOn() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bool on = 2;</code>
             */
            public boolean getOn() {
                return on_;
            }

            /**
             * <code>optional bool on = 2;</code>
             */
            public Builder setOn(boolean value) {
                bitField0_ |= 0x00000002;
                on_ = value;

                return this;
            }

            /**
             * <code>optional bool on = 2;</code>
             */
            public Builder clearOn() {
                bitField0_ = (bitField0_ & ~0x00000002);
                on_ = false;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:smart_push_config)
        }

        static {
            defaultInstance = new smart_push_config(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:smart_push_config)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
