package com.ble.lib.x2.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt_user_target.proto

public final class BtUserTarget {
    private BtUserTarget() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface bt_user_targetOrBuilder extends
            // @@protoc_insertion_point(interface_extends:bt_user_target)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint32 target_sleep = 1;</code>
         * <p/>
         * <pre>
         * second
         * </pre>
         */
        boolean hasTargetSleep();

        /**
         * <code>optional uint32 target_sleep = 1;</code>
         * <p/>
         * <pre>
         * second
         * </pre>
         */
        int getTargetSleep();

        /**
         * <code>optional uint32 target_energy = 2;</code>
         * <p/>
         * <pre>
         * kcal
         * </pre>
         */
        boolean hasTargetEnergy();

        /**
         * <code>optional uint32 target_energy = 2;</code>
         * <p/>
         * <pre>
         * kcal
         * </pre>
         */
        int getTargetEnergy();
    }

    /**
     * Protobuf type {@code bt_user_target}
     */
    public static final class bt_user_target extends
            com.google.protobuf.GeneratedMessageLite implements
            // @@protoc_insertion_point(message_implements:bt_user_target)
            bt_user_targetOrBuilder {
        // Use bt_user_target.newBuilder() to construct.
        private bt_user_target(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private bt_user_target(boolean noInit) {
            this.unknownFields = com.google.protobuf.ByteString.EMPTY;
        }

        private static final bt_user_target defaultInstance;

        public static bt_user_target getDefaultInstance() {
            return defaultInstance;
        }

        public bt_user_target getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.ByteString unknownFields;

        private bt_user_target(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.ByteString.Output unknownFieldsOutput =
                    com.google.protobuf.ByteString.newOutput();
            com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
                    com.google.protobuf.CodedOutputStream.newInstance(
                            unknownFieldsOutput);
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            targetSleep_ = input.readUInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            targetEnergy_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                try {
                    unknownFieldsCodedOutput.flush();
                } catch (java.io.IOException e) {
                    // Should not happen
                } finally {
                    unknownFields = unknownFieldsOutput.toByteString();
                }
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<bt_user_target> PARSER =
                new com.google.protobuf.AbstractParser<bt_user_target>() {
                    public bt_user_target parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new bt_user_target(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<bt_user_target> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int TARGET_SLEEP_FIELD_NUMBER = 1;
        private int targetSleep_;

        /**
         * <code>optional uint32 target_sleep = 1;</code>
         * <p/>
         * <pre>
         * second
         * </pre>
         */
        public boolean hasTargetSleep() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional uint32 target_sleep = 1;</code>
         * <p/>
         * <pre>
         * second
         * </pre>
         */
        public int getTargetSleep() {
            return targetSleep_;
        }

        public static final int TARGET_ENERGY_FIELD_NUMBER = 2;
        private int targetEnergy_;

        /**
         * <code>optional uint32 target_energy = 2;</code>
         * <p/>
         * <pre>
         * kcal
         * </pre>
         */
        public boolean hasTargetEnergy() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional uint32 target_energy = 2;</code>
         * <p/>
         * <pre>
         * kcal
         * </pre>
         */
        public int getTargetEnergy() {
            return targetEnergy_;
        }

        private void initFields() {
            targetSleep_ = 0;
            targetEnergy_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, targetSleep_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt32(2, targetEnergy_);
            }
            output.writeRawBytes(unknownFields);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, targetSleep_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, targetEnergy_);
            }
            size += unknownFields.size();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static bt_user_target parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_user_target parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_user_target parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static bt_user_target parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static bt_user_target parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_user_target parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static bt_user_target parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static bt_user_target parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static bt_user_target parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static bt_user_target parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(bt_user_target prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code bt_user_target}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        bt_user_target, Builder>
                implements
                // @@protoc_insertion_point(builder_implements:bt_user_target)
                bt_user_targetOrBuilder {
            // Construct using BtUserTarget.bt_user_target.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                targetSleep_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                targetEnergy_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public bt_user_target getDefaultInstanceForType() {
                return bt_user_target.getDefaultInstance();
            }

            public bt_user_target build() {
                bt_user_target result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public bt_user_target buildPartial() {
                bt_user_target result = new bt_user_target(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.targetSleep_ = targetSleep_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.targetEnergy_ = targetEnergy_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(bt_user_target other) {
                if (other == bt_user_target.getDefaultInstance()) return this;
                if (other.hasTargetSleep()) {
                    setTargetSleep(other.getTargetSleep());
                }
                if (other.hasTargetEnergy()) {
                    setTargetEnergy(other.getTargetEnergy());
                }
                setUnknownFields(
                        getUnknownFields().concat(other.unknownFields));
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                bt_user_target parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (bt_user_target) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int targetSleep_;

            /**
             * <code>optional uint32 target_sleep = 1;</code>
             * <p/>
             * <pre>
             * second
             * </pre>
             */
            public boolean hasTargetSleep() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional uint32 target_sleep = 1;</code>
             * <p/>
             * <pre>
             * second
             * </pre>
             */
            public int getTargetSleep() {
                return targetSleep_;
            }

            /**
             * <code>optional uint32 target_sleep = 1;</code>
             * <p/>
             * <pre>
             * second
             * </pre>
             */
            public Builder setTargetSleep(int value) {
                bitField0_ |= 0x00000001;
                targetSleep_ = value;

                return this;
            }

            /**
             * <code>optional uint32 target_sleep = 1;</code>
             * <p/>
             * <pre>
             * second
             * </pre>
             */
            public Builder clearTargetSleep() {
                bitField0_ = (bitField0_ & ~0x00000001);
                targetSleep_ = 0;

                return this;
            }

            private int targetEnergy_;

            /**
             * <code>optional uint32 target_energy = 2;</code>
             * <p/>
             * <pre>
             * kcal
             * </pre>
             */
            public boolean hasTargetEnergy() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional uint32 target_energy = 2;</code>
             * <p/>
             * <pre>
             * kcal
             * </pre>
             */
            public int getTargetEnergy() {
                return targetEnergy_;
            }

            /**
             * <code>optional uint32 target_energy = 2;</code>
             * <p/>
             * <pre>
             * kcal
             * </pre>
             */
            public Builder setTargetEnergy(int value) {
                bitField0_ |= 0x00000002;
                targetEnergy_ = value;

                return this;
            }

            /**
             * <code>optional uint32 target_energy = 2;</code>
             * <p/>
             * <pre>
             * kcal
             * </pre>
             */
            public Builder clearTargetEnergy() {
                bitField0_ = (bitField0_ & ~0x00000002);
                targetEnergy_ = 0;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:bt_user_target)
        }

        static {
            defaultInstance = new bt_user_target(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:bt_user_target)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
